require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  Include:
    - '**/Rakefile'

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/fedora_migrate/rights_metadata.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/fedora_migrate/rights_metadata.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'lib/fedora_migrate/rights_metadata.rb'

Metrics/ModuleLength:
  Exclude:

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Exclude:

Style/LineEndConcatenation:
  Exclude:

Style/PredicateName:
  Exclude:

Style/GlobalVars:
  Exclude:
    - 'spec/**/*'

Style/SingleLineBlockParams:
  Enabled: false

Style/ClassVars:
  Exclude:

Style/SignalException:
  Enabled: false

Rails/Output:
  Exclude:

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:

Style/FileName:
  Exclude:
    - 'lib/fedora-migrate.rb'

Style/VariableName:
  Exclude:
    - 'lib/fedora_migrate/permissions_mover.rb'
